# src/main.py
import sys, os, threading, time
sys.path.insert(0, os.path.dirname(__file__))

from detection.config import Config
from detection.pipeline import CameraWorker
from dashboard.app import app, register_worker, load_cameras, start_retention_thread

# shared model lock for multi-camera
import torch
_model_lock = threading.Lock()

def start_worker(cam_config):
    cfg              = Config()
    cfg.CAMERA_ID    = cam_config["id"]
    cfg.ROOM_NAME    = cam_config["room"]
    cfg.CAMERA_SOURCE = cam_config["source"]
    cfg.VIOLENCE_THRESHOLD = float(cam_config.get("threshold", 0.7))

    worker = CameraWorker(cfg)
    register_worker(cfg.CAMERA_ID, worker)

    t = threading.Thread(target=worker.run, daemon=True)
    t.start()
    print(f"[MAIN] Started worker for {cfg.CAMERA_ID} — {cfg.ROOM_NAME}")
    return worker


def _ssl_context():
    """
    Look for a self-signed cert generated by src/certs/generate_cert.py.
    Serving over HTTPS is what lets the browser run "secure context" APIs
    (Notification, etc.) -- see src/certs/README.md for how to generate
    one and why a self-signed cert is the right tool for a facility's
    local network specifically (not for open-internet deployment).

    Paths can be overridden via HAVEN_SSL_CERT / HAVEN_SSL_KEY env vars,
    e.g. to point at a real cert from a reverse proxy setup instead.
    Falls back to plain HTTP (returns None) if no cert is present, so a
    fresh checkout still runs without extra setup -- it just won't have
    secure-context browser features until a cert is generated.
    """
    certs_dir = os.path.join(os.path.dirname(__file__), "certs")
    cert_path = os.environ.get("HAVEN_SSL_CERT", os.path.join(certs_dir, "cert.pem"))
    key_path = os.environ.get("HAVEN_SSL_KEY", os.path.join(certs_dir, "key.pem"))
    if os.path.exists(cert_path) and os.path.exists(key_path):
        return (cert_path, key_path)
    print(
        "[MAIN] No TLS cert found at "
        f"{cert_path} -- serving over plain HTTP.\n"
        "[MAIN] Desktop notifications and other secure-context browser "
        "features won't work until you generate one: "
        "python src/certs/generate_cert.py"
    )
    return None


def run_dashboard():
    port = int(os.environ.get("PORT", 5000))
    ssl_context = _ssl_context()
    scheme = "https" if ssl_context else "http"
    print(f"[MAIN] Dashboard starting at {scheme}://localhost:{port}")
    app.run(host="0.0.0.0", port=port, debug=False, use_reloader=False, ssl_context=ssl_context)


if __name__ == "__main__":
    # start dashboard
    t = threading.Thread(target=run_dashboard, daemon=True)
    t.start()
    time.sleep(2)

    # Age-based cleanup of old incident records / clip files. Runs once
    # now, then once a day -- see dashboard/retention.py and the
    # retention_days / false_positive_retention_days System Settings.
    start_retention_thread()

    # start a worker for every camera in cameras.json
    cameras = load_cameras()
    workers = []
    for cam in cameras:
        w = start_worker(cam)
        workers.append(w)

    print(f"[MAIN] {len(workers)} camera(s) running. Press Ctrl+C to stop.")

    # keep main thread alive
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("[MAIN] Shutting down.")